#!/bin/bash
sudo systemctl start bluetooth
counter=0
available_devices=()
for i in $(bluetoothctl scan on)
do
    IFS="Device | " read -ra mac_addr <<< "$i"
    
    output=$available_wifis[$counter]
    echo "$counter ${available_wifis[$counter]}"
    ((counter++))
done